apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    api:
      insecure: false
      dashboard: true
    ports:
      traefik:
        expose:
          default: true
