apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    api:
      insecure: false
      dashboard: true
    additionalArguments:
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.filters.statuscodes=100-599"
      - "--accesslog.fields.headers.defaultmode=drop"
    experimental:
      plugins:
        bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.4.5
    volumes:
      - name: crowdsec-bouncer-key
        mountPath: /etc/traefik/crowdsec
        type: secret
        secretName: crowdsec-bouncer-key
    metrics:
      prometheus:
        addRoutersLabels: true
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: "4"
        memory: 8Gi
    ports:
      traefik:
        expose:
          default: false
    service:
      spec:
        externalTrafficPolicy: Local
