apiVersion: v1
kind: Secret
metadata:
  name: kasia-cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:UAUxWs2bY7hBAU4LBbQ7ooHrYbNaRMyy8hIdAMdv2gKrx7HPfrKvAw==,iv:cq9jA9nuGMK8Z39j5QIFMPRa/RfllbRO0ottLkE4uaY=,tag:uUsvtfpaFpCgsuXMfCFZQA==,type:str]
sops:
  age:
    - recipient: age1wk2gy8cquajzw70pzt9jlg0az96yzg5mzagj82m4098p59zju4qq3kyc6z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRFBrd1dxSUVrL3luaER3
        SW0vOU9nN0lpTGluTk5VNWY0UVY2Zkl4d1RjClg5RHoxY1ZHT2RMWFIwY0M2Y1I3
        NTNyc3F2RDVYWVBDMzRqSFpwams4S2sKLS0tIHR5Qml4UUxpZFBoMHJNTTZ1TTlD
        YUxXTDdjVENKY3VSNlQ4eUhSQzByYzQKHLI+1CO4XyIYoLyFxg1L3l5xjlxew+/D
        9yd+8Q3RujX+n9j2xau/xfX5CqXKcdq1MwQXnajh5Au6L+P8tzGIqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-21T02:25:40Z"
  mac: ENC[AES256_GCM,data:RVlJnKdW4YhvqdRx8WqOjxeQbhw2R5qG5wISkgN7ed/LEt30c1ZAwFnfh0SJygo1jLuv4Tf3rXFI35gGmPg4rbeP/gMpGsm+g2byeNCeD0goYSm4VKR7HI3bkbwo945+GBBpAEk856wK2X5aa6OvwKaR/wqQ0diG6RepZ5eVAz4=,iv:Ty1enzolhKIXEEtWBU8VCT4xIuUOvCUeZGx1HVabQXU=,tag:U0OgpLkLErP5iaHXG90qUw==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.10.2
