apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: kluster
  source:
    repoURL: https://github.com/minio/operator.git
    targetRevision: v7.1.1
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
