apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: main
  namespace: minio
spec:
  configuration:
    name: storage-configuration
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: main
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: minio
  name: minio-frontend
  labels:
    v1.min.io/tenant: main
spec:
  ports:
    - name: http-minio
      port: 80
      targetPort: 9443
  selector:
    v1.min.io/tenant: main
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-dashboard
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio.kasia.fyi`)
      kind: Rule
      services:
        - name: main-console
          port: 9443
          serversTransport: main-console
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: main-console
spec:
  insecureSkipVerify: true
