apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data2-prod-indexer-0
  namespace: kaspa
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
