apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kaspad
  namespace: kaspa
spec:
  serviceName: prod-kaspad
  selector:
    matchLabels:
      app: prod-kaspad
  template:
    metadata:
      labels:
        app: prod-kaspad
    spec:
      containers:
        - name: kaspad
          ports:
            - name: grpc
              containerPort: 16110
              protocol: TCP
            - name: rpc
              containerPort: 16110
              protocol: TCP
            - name: wrpc-borsh
              containerPort: 17110
              protocol: TCP
            - name: wrpc-json
              containerPort: 18112
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 350Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kaspad
  namespace: kaspa
  labels:
    app: prod-kaspad
spec:
  selector:
    app: prod-kaspad
