apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: crowdsec-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./bouncer-keys.enc.yaml
