apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: indexer
  namespace: kaspa
spec:
  # Headless service for stable network IDs in the StatefulSet
  clusterIP: None
  selector:
    app: indexer
  ports:
    - name: rpc
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexer
  namespace: kaspa
spec:
  serviceName: indexer
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: indexer
          image: kkluster/kasia-indexer@sha256:cd0b9099ac0117c7a10819b947577e21a4cac0ab605c4b5ef943ec72651d931b
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_BACKTRACE
              value: '1'
            - name: RUST_LOG
              value: 'info'
            - name: 'KASIA_INDEXER_DB_ROOT'
              value: '/app/data'
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/data
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: longhorn
        resources:
          requests:
            storage: 100Gi
