apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crowdsec-lapi
  namespace: monitoring
  labels:
    release: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - crowdsec
  selector:
    matchLabels:
      app: crowdsec-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crowdsec-agent
  namespace: monitoring
  labels:
    release: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - crowdsec
  selector:
    matchLabels:
      app: crowdsec-agent-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
