apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-backend
  namespace: monitoring
  labels:
    release: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - longhorn
  selector:
    matchLabels:
      app: longhorn-manager
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/name: longhorn
  endpoints:
    - port: manager
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
