apiVersion: v1
kind: Service
metadata:
  name: kaspad
  labels:
    app: kaspad
  namespace: kaspa
spec:
  # Headless service for stable network IDs in the StatefulSet
  clusterIP: None
  selector:
    app: kaspad
  ports:
    - name: rpc
      port: 16110
      targetPort: 16110
      protocol: TCP
    - name: grpc
      port: 16111
      targetPort: 16111
      protocol: TCP
    - name: wrpc-borsh
      port: 17110
      targetPort: 17110
      protocol: TCP
    - name: wrpc-json
      port: 18112
      targetPort: 18112
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kaspad
  namespace: kaspa
spec:
  serviceName: kaspad
  replicas: 1
  selector:
    matchLabels:
      app: kaspad
  template:
    metadata:
      labels:
        app: kaspad
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: kaspad
          image: supertypo/rusty-kaspad:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_BACKTRACE
              value: '1'
          # Container listens on these ports
          ports:
            - name: rpc
              containerPort: 16110
              protocol: TCP
            - name: grpc
              containerPort: 16111
              protocol: TCP
            - name: wrpc-borsh
              containerPort: 17110
              protocol: TCP
            - name: wrpc-json
              containerPort: 18112
              protocol: TCP
          args:
            - kaspad
            - --yes
            - --nologfiles
            - --disable-upnp
            - --utxoindex
            - --rpclisten=0.0.0.0:16110
            - --rpclisten-borsh=0.0.0.0:17110
            - --rpclisten-json=0.0.0.0:18112
            - --externalip=78.47.96.208
          volumeMounts:
            - name: data
              mountPath: /app/data
          readinessProbe:
            tcpSocket:
              port: 16110
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 16110
            initialDelaySeconds: 30
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: longhorn
        resources:
          requests:
            storage: 200Gi
